# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ostools
                                 A QGIS plugin
 ciao
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-09
        copyright            : (C) 2025 by unibo
        email                : gianluca.lelli2@unibo.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'unibo'
__date__ = '2025-07-09'
__copyright__ = '(C) 2025 by unibo'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ostools class from file ostools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ostools import ostoolsPlugin
    return ostoolsPlugin()
